CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL CHECK (
        type IN (
            'follow',
            'follow_request',
            'group_invite',
            'group_request',
            'group_activity',
            'event',
            'message',
            'comment',
            'post'
        )
    ),
    related_id BIGINT,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_user_created_at
    ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread
    ON notifications (user_id, is_read)
    WHERE is_read = FALSE;
CREATE INDEX idx_notifications_type ON notifications (type);
