package migrations

import (
	"strings"
	"testing"
)

func TestDefinitionsIncludesPostgreSQLNotificationSchema(t *testing.T) {
	definitions, err := Definitions()
	if err != nil {
		t.Fatalf("Definitions returned an error: %v", err)
	}
	if len(definitions) != 1 {
		t.Fatalf("expected one migration, got %d", len(definitions))
	}

	migration := definitions[0]
	if migration.Version != "000001_initial" {
		t.Fatalf("unexpected version: %q", migration.Version)
	}
	for _, expected := range []string{"GENERATED BY DEFAULT AS IDENTITY", "TIMESTAMPTZ", "group_activity"} {
		if !strings.Contains(migration.SQL, expected) {
			t.Errorf("migration does not contain %q", expected)
		}
	}
	if len(migration.Checksum) != 64 {
		t.Fatalf("expected SHA-256 checksum, got %q", migration.Checksum)
	}
}
